function gkFill( x, y)
%GKFILL wrapper to fill function
    fill(x,y,gkGet('faceColor'),...
        'EdgeColor',gkGet('edgeColor'),...
        'LineStyle',gkGet('edgeStyle'),...
        'LineWidth',gkGet('edgeWidth'));
end

