Splines::Spline2D
std::string Splines::Spline2D::m_name
SplineSurf* Splines::Spline2D::m_pSpline2D
Splines::Spline2D::Spline2D(string const &name="Spline2D")
spline constructor
Splines::Spline2D::~Spline2D()
bool Splines::Spline2D::is_x_closed() const
void Splines::Spline2D::make_x_closed()
void Splines::Spline2D::make_x_opened()
bool Splines::Spline2D::is_y_closed() const
void Splines::Spline2D::make_y_closed()
void Splines::Spline2D::make_y_opened()
bool Splines::Spline2D::is_x_bounded() const
void Splines::Spline2D::make_x_unbounded()
void Splines::Spline2D::make_x_bounded()
bool Splines::Spline2D::is_y_bounded() const
void Splines::Spline2D::make_y_unbounded()
void Splines::Spline2D::make_y_bounded()
string const& Splines::Spline2D::name() const
void Splines::Spline2D::clear()
Cancel the support points, empty the spline.
integer Splines::Spline2D::numPointX() const
return the number of support points of the spline along x direction
integer Splines::Spline2D::numPointY() const
return the number of support points of the spline along y direction
real_type Splines::Spline2D::xNode(integer i) const
return the i-th node of the spline (x component).
real_type Splines::Spline2D::yNode(integer i) const
return the i-th node of the spline (y component).
real_type Splines::Spline2D::zNode(integer i, integer j) const
return the i-th node of the spline (y component).
real_type Splines::Spline2D::xMin() const
return x-minumum spline value
real_type Splines::Spline2D::xMax() const
return x-maximum spline value
real_type Splines::Spline2D::yMin() const
return y-minumum spline value
real_type Splines::Spline2D::yMax() const
return y-maximum spline value
real_type Splines::Spline2D::zMin() const
return z-minumum spline value
real_type Splines::Spline2D::zMax() const
return z-maximum spline value
void Splines::Spline2D::build(SplineType2D tp, real_type const *x, integer incx, real_type const *y, integer incy, real_type const *z, integer ldZ, integer nx, integer ny, bool fortran_storage=false, bool transposed=false)
Referenced by build, setup.
void Splines::Spline2D::build(SplineType2D tp, vector< real_type > const &x, vector< real_type > const &y, vector< real_type > const &z, bool fortran_storage=false, bool transposed=false)
Build surface spline.
tp spline type x vector of x-coordinates, nx = x.size() y vector of y-coordinates, ny = y.size() z matrix of z-values. Elements are stored by row Z(i,j) = z[i*ny+j] as C-matrix fortran_storage if true elements are stored by column i.e. Z(i,j) = z[i+j*nx] as Fortran-matrix transposed if true matrix Z is stored transposed
void Splines::Spline2D::build(SplineType2D tp, real_type const *z, integer ldZ, integer nx, integer ny, bool fortran_storage=false, bool transposed=false)
Build surface spline.
tp spline type z matrix of z-values. Elements are stored by row Z(i,j) = z[i*ny+j] as C-matrix ldZ leading dimension of the matrix. Elements are stored by row Z(i,j) = z[i*ldZ+j] as C-matrix nx x-dimension ny y-dimension fortran_storage if true elements are stored by column i.e. Z(i,j) = z[i+j*nx] as Fortran-matrix transposed if true matrix Z is stored transposed
void Splines::Spline2D::build(SplineType2D tp, vector< real_type > const &z, integer nx, integer ny, bool fortran_storage=false, bool transposed=false)
Build surface spline.
tp spline type z matrix of z-values. Elements are stored by row Z(i,j) = z[i*ny+j] as C-matrix. ldZ leading dimension of the matrix is ny for C-storage and nx for Fortran storage. nx x-dimension ny y-dimension fortran_storage if true elements are stored by column i.e. Z(i,j) = z[i+j*nx] as Fortran-matrix transposed if true matrix Z is stored transposed
void Splines::Spline2D::setup(GenericContainer const &gc)
void Splines::Spline2D::build(GenericContainer const &gc)
real_type Splines::Spline2D::operator()(real_type x, real_type y) const
Evaluate spline value.
void Splines::Spline2D::D(real_type x, real_type y, real_type d[3]) const
First derivative.
real_type Splines::Spline2D::Dx(real_type x, real_type y) const
Referenced by eval_D_1.
real_type Splines::Spline2D::Dy(real_type x, real_type y) const
Referenced by eval_D_2.
void Splines::Spline2D::DD(real_type x, real_type y, real_type dd[6]) const
Second derivative.
real_type Splines::Spline2D::Dxx(real_type x, real_type y) const
Referenced by eval_D_1_1.
real_type Splines::Spline2D::Dxy(real_type x, real_type y) const
Referenced by eval_D_1_2.
real_type Splines::Spline2D::Dyy(real_type x, real_type y) const
Referenced by eval_D_2_2.
real_type Splines::Spline2D::eval(real_type x, real_type y) const
Evaluate spline value.
real_type Splines::Spline2D::eval_D_1(real_type x, real_type y) const
First derivative.
real_type Splines::Spline2D::eval_D_2(real_type x, real_type y) const
real_type Splines::Spline2D::eval_D_1_1(real_type x, real_type y) const
Second derivative.
real_type Splines::Spline2D::eval_D_1_2(real_type x, real_type y) const
real_type Splines::Spline2D::eval_D_2_2(real_type x, real_type y) const
void Splines::Spline2D::writeToStream(ostream_type &s) const
Print spline coefficients.
char const* Splines::Spline2D::type_name() const
Return spline typename.
string Splines::Spline2D::info() const
void Splines::Spline2D::info(ostream_type &stream) const