Splines::SplineSurf
Utils::Malloc<real_type> Splines::SplineSurf::m_mem
string const Splines::SplineSurf::m_name
bool Splines::SplineSurf::m_x_closed
bool Splines::SplineSurf::m_y_closed
bool Splines::SplineSurf::m_x_can_extend
bool Splines::SplineSurf::m_y_can_extend
integer Splines::SplineSurf::m_nx
integer Splines::SplineSurf::m_ny
real_type* Splines::SplineSurf::m_X
real_type* Splines::SplineSurf::m_Y
real_type* Splines::SplineSurf::m_Z
real_type Splines::SplineSurf::m_Z_min
real_type Splines::SplineSurf::m_Z_max
Utils::BinarySearch<integer> Splines::SplineSurf::m_bs_x
Utils::BinarySearch<integer> Splines::SplineSurf::m_bs_y
Splines::SplineSurf::SplineSurf(SplineSurf const &)=delete
SplineSurf const& Splines::SplineSurf::operator=(SplineSurf const &)=delete
integer Splines::SplineSurf::search_x(real_type &x) const
integer Splines::SplineSurf::search_y(real_type &y) const
void Splines::SplineSurf::initLastInterval_x()
void Splines::SplineSurf::initLastInterval_y()
integer Splines::SplineSurf::ipos_C(integer i, integer j, integer ldZ) const
integer Splines::SplineSurf::ipos_F(integer i, integer j, integer ldZ) const
integer Splines::SplineSurf::ipos_C(integer i, integer j) const
integer Splines::SplineSurf::ipos_F(integer i, integer j) const
virtual void Splines::SplineSurf::makeSpline()=0
Splines::SplineSurf::SplineSurf(string const &name="Spline")
spline constructor
Splines::SplineSurf::~SplineSurf()
spline destructor
bool Splines::SplineSurf::is_x_closed() const
Referenced by Splines::Spline2D::is_x_closed.
void Splines::SplineSurf::make_x_closed()
Referenced by Splines::Spline2D::make_x_closed.
void Splines::SplineSurf::make_x_opened()
Referenced by Splines::Spline2D::make_x_opened.
bool Splines::SplineSurf::is_y_closed() const
Referenced by Splines::Spline2D::is_y_closed.
void Splines::SplineSurf::make_y_closed()
Referenced by Splines::Spline2D::make_y_closed.
void Splines::SplineSurf::make_y_opened()
Referenced by Splines::Spline2D::make_y_opened.
bool Splines::SplineSurf::is_x_bounded() const
Referenced by Splines::Spline2D::is_x_bounded.
void Splines::SplineSurf::make_x_unbounded()
Referenced by Splines::Spline2D::make_x_unbounded.
void Splines::SplineSurf::make_x_bounded()
Referenced by Splines::Spline2D::make_x_bounded.
bool Splines::SplineSurf::is_y_bounded() const
Referenced by Splines::Spline2D::is_y_bounded.
void Splines::SplineSurf::make_y_unbounded()
Referenced by Splines::Spline2D::make_y_unbounded.
void Splines::SplineSurf::make_y_bounded()
Referenced by Splines::Spline2D::make_y_bounded.
string const& Splines::SplineSurf::name() const
Referenced by info, Splines::Spline2D::name.
void Splines::SplineSurf::clear()
Cancel the support points, empty the spline.
Referenced by Splines::Spline2D::clear.
integer Splines::SplineSurf::numPointX() const
return the number of support points of the spline along x direction
Referenced by Splines::Spline2D::numPointX.
integer Splines::SplineSurf::numPointY() const
return the number of support points of the spline along y direction
Referenced by Splines::Spline2D::numPointY.
real_type Splines::SplineSurf::xNode(integer i) const
return the i-th node of the spline (x component).
Referenced by Splines::Spline2D::xNode.
real_type Splines::SplineSurf::yNode(integer i) const
return the i-th node of the spline (y component).
Referenced by Splines::Spline2D::yNode.
real_type Splines::SplineSurf::zNode(integer i, integer j) const
return the i-th node of the spline (y component).
Referenced by Splines::Spline2D::zNode.
real_type Splines::SplineSurf::xMin() const
return x-minumum spline value
Referenced by Splines::Spline2D::xMin.
real_type Splines::SplineSurf::xMax() const
return x-maximum spline value
Referenced by Splines::Spline2D::xMax.
real_type Splines::SplineSurf::yMin() const
return y-minumum spline value
Referenced by Splines::Spline2D::yMin.
real_type Splines::SplineSurf::yMax() const
return y-maximum spline value
Referenced by Splines::Spline2D::yMax.
real_type Splines::SplineSurf::zMin() const
return z-minumum spline value
Referenced by Splines::Spline2D::zMin.
real_type Splines::SplineSurf::zMax() const
return z-maximum spline value
Referenced by Splines::Spline2D::zMax.
void Splines::SplineSurf::build(real_type const *x, integer incx, real_type const *y, integer incy, real_type const *z, integer ldZ, integer nx, integer ny, bool fortran_storage=false, bool transposed=false)
Build surface spline x vector of x-coordinates incx access elements as x[0], x[incx], x[2*incx],... y vector of y-coordinates incy access elements as y[0], y[incy], x[2*incy],... z matrix of z-values ldZ leading dimension of the matrix. Elements are stored by row Z(i,j) = z[i*ldZ+j] as C-matrix nx total number of points in direction x ny total number of points in direction y fortran_storage if true elements are stored by column i.e. Z(i,j) = z[i+j*ldZ] as Fortran-matrix transposed if true matrix Z is stored transposed
Referenced by build, setup.
void Splines::SplineSurf::build(vector< real_type > const &x, vector< real_type > const &y, vector< real_type > const &z, bool fortran_storage=false, bool transposed=false)
Build surface spline x vector of x-coordinates, nx = x.size() y vector of y-coordinates, ny = y.size() z matrix of z-values. Elements are stored by row Z(i,j) = z[i*ny+j] as C-matrix fortran_storage if true elements are stored by column i.e. Z(i,j) = z[i+j*nx] as Fortran-matrix transposed if true matrix Z is stored transposed
void Splines::SplineSurf::build(real_type const *z, integer ldZ, integer nx, integer ny, bool fortran_storage=false, bool transposed=false)
Build surface spline.
z matrix of z-values. Elements are stored by row Z(i,j) = z[i*ny+j] as C-matrix ldZ leading dimension of the matrix. Elements are stored by row Z(i,j) = z[i*ldZ+j] as C-matrix nx x-dimension ny y-dimension fortran_storage if true elements are stored by column i.e. Z(i,j) = z[i+j*nx] as Fortran-matrix transposed if true matrix Z is stored transposed
void Splines::SplineSurf::build(vector< real_type > const &z, integer nx, integer ny, bool fortran_storage=false, bool transposed=false)
Build surface spline.
z matrix of z-values. Elements are stored by row Z(i,j) = z[i*ny+j] as C-matrix. ldZ leading dimension of the matrix is ny for C-storage and nx for Fortran storage. nx x-dimension ny y-dimension fortran_storage if true elements are stored by column i.e. Z(i,j) = z[i+j*nx] as Fortran-matrix transposed if true matrix Z is stored transposed
void Splines::SplineSurf::setup(GenericContainer const &gc)
Referenced by build.
void Splines::SplineSurf::build(GenericContainer const &gc)
virtual real_type Splines::SplineSurf::operator()(real_type x, real_type y) const =0
Evaluate spline value at point $ (x,y) $.
virtual void Splines::SplineSurf::D(real_type x, real_type y, real_type d[3]) const =0
value and first derivatives at point $ (x,y) $ d[0] value of the spline $ S(x,y) $ d[1] derivative respect to $ x $ of the spline: $ S_x(x,y) $ d[2] derivative respect to $ y $ of the spline: $ S_y(x,y) $
Referenced by Splines::Spline2D::D.
virtual real_type Splines::SplineSurf::Dx(real_type x, real_type y) const =0
first derivatives respect to $ x $ at point $ (x,y) $ of the spline: $ S_x(x,y) $
Referenced by Splines::Spline2D::Dx, eval_D_1.
virtual real_type Splines::SplineSurf::Dy(real_type x, real_type y) const =0
first derivatives respect to $ y $ at point $ (x,y) $ of the spline: $ S_y(x,y) $
Referenced by Splines::Spline2D::Dy, eval_D_2.
virtual void Splines::SplineSurf::DD(real_type x, real_type y, real_type dd[6]) const =0
value, first and second derivatives at point $ (x,y) $ d[0] value of the spline $ S(x,y) $ d[1] derivative respect to $ x $ of the spline: $ S_x(x,y) $ d[2] derivative respect to $ y $ of the spline: $ S_y(x,y) $ d[3] second derivative respect to $ x $ of the spline: $ S_{xx}(x,y) $ d[4] mixed second derivative: $ S_{xy}(x,y) $ d[5] second derivative respect to $ y $ of the spline: $ S_{yy}(x,y) $
Referenced by Splines::Spline2D::DD.
virtual real_type Splines::SplineSurf::Dxx(real_type x, real_type y) const =0
second derivatives respect to $ x $ at point $ (x,y) $ of the spline: $ S_{xx}(x,y) $
Referenced by Splines::Spline2D::Dxx, eval_D_1_1.
virtual real_type Splines::SplineSurf::Dxy(real_type x, real_type y) const =0
mixed second derivatives: $ S_{xy}(x,y) $
Referenced by Splines::Spline2D::Dxy, eval_D_1_2.
virtual real_type Splines::SplineSurf::Dyy(real_type x, real_type y) const =0
second derivatives respect to $ y $ at point $ (x,y) $ of the spline: $ S_{yy}(x,y) $
Referenced by Splines::Spline2D::Dyy, eval_D_2_2.
real_type Splines::SplineSurf::eval(real_type x, real_type y) const
Evaluate spline value at point $ (x,y) $.
real_type Splines::SplineSurf::eval_D_1(real_type x, real_type y) const
Alias for Dx(x,y)
real_type Splines::SplineSurf::eval_D_2(real_type x, real_type y) const
Alias for Dy(x,y)
real_type Splines::SplineSurf::eval_D_1_1(real_type x, real_type y) const
Alias for Dxx(x,y)
real_type Splines::SplineSurf::eval_D_1_2(real_type x, real_type y) const
Alias for Dxy(x,y)
real_type Splines::SplineSurf::eval_D_2_2(real_type x, real_type y) const
Alias for Dyy(x,y)
virtual void Splines::SplineSurf::writeToStream(ostream_type &s) const =0
Print spline coefficients.
Referenced by Splines::Spline2D::writeToStream.
virtual char const* Splines::SplineSurf::type_name() const =0
Return spline typename.
Referenced by info, Splines::Spline2D::type_name.
string Splines::SplineSurf::info() const
return a string with information about the spline.
Referenced by Splines::Spline2D::info, info.
void Splines::SplineSurf::info(ostream_type &stream) const
write a string with information about the spline.