Splines::SplineSet
string const Splines::SplineSet::m_name
Utils::Malloc<real_type> Splines::SplineSet::m_baseValue
Utils::Malloc<real_type*> Splines::SplineSet::m_basePointer
Utils::Malloc<void*> Splines::SplineSet::m_baseSplines
Utils::Malloc<int> Splines::SplineSet::m_baseInt
integer Splines::SplineSet::m_npts
integer Splines::SplineSet::m_nspl
real_type* Splines::SplineSet::m_X
real_type** Splines::SplineSet::m_Y
real_type** Splines::SplineSet::m_Yp
real_type** Splines::SplineSet::m_Ypp
real_type* Splines::SplineSet::m_Ymin
real_type* Splines::SplineSet::m_Ymax
Spline** Splines::SplineSet::m_splines
int* Splines::SplineSet::m_is_monotone
BinarySearch Splines::SplineSet::m_header_to_position
Splines::SplineSet::SplineSet(SplineSet const &)=delete
SplineSet const& Splines::SplineSet::operator=(SplineSet const &)=delete
Spline const * Splines::SplineSet::intersect(integer spl, real_type zeta, real_type &x) const
| find x value such that the monotone spline | (spline[spl])(x) intersect the value zeta
Splines::SplineSet::SplineSet(string const &name="SplineSet")
spline constructor
Splines::SplineSet::~SplineSet()
spline destructor
string const& Splines::SplineSet::name() const
Referenced by info, name_list.
string const& Splines::SplineSet::header(integer i) const
Referenced by dump_table.
void Splines::SplineSet::get_headers(std::vector< std::string > &names) const
fill a vector of strings with the names of the splines
string Splines::SplineSet::name_list() const
Referenced by getPosition.
int Splines::SplineSet::isMonotone(integer i) const
integer Splines::SplineSet::numPoints() const
return the number of support points of the splines
integer Splines::SplineSet::numSplines() const
return the number splines in the spline set
integer Splines::SplineSet::getPosition(char const *hdr) const
return the column with header(i) == hdr, return -1 if not found
Referenced by eval2, eval2_D, eval2_DD, eval2_DDD, getSpline, yMax, yMin.
real_type const* Splines::SplineSet::xNodes() const
return the vector of values of x-nodes
real_type const * Splines::SplineSet::yNodes(integer i) const
return the vector of values of x-nodes
real_type Splines::SplineSet::xNode(integer npt) const
return the i-th node of the spline (x component).
real_type Splines::SplineSet::yNode(integer npt, integer spl) const
return the i-th node of the spline (y component).
real_type Splines::SplineSet::xMin() const
return x-minumum spline value
Referenced by dump_table.
real_type Splines::SplineSet::xMax() const
return x-maximum spline value
Referenced by dump_table.
real_type Splines::SplineSet::yMin(integer spl) const
return y-minumum spline value
real_type Splines::SplineSet::yMax(integer spl) const
return y-maximum spline value
real_type Splines::SplineSet::yMin(char const *spl) const
return y-minumum spline value
real_type Splines::SplineSet::yMax(char const *spl) const
return y-maximum spline value
Spline * Splines::SplineSet::getSpline(integer i) const
Return pointer to the i-th spline.
Referenced by D, DD, DDD, DDDD, DDDDD, eval, eval2, eval2_D, eval2_DD, eval2_DDD, eval_D, eval_DD, eval_DDD, eval_DDDD, eval_DDDDD, operator().
Spline* Splines::SplineSet::getSpline(char const *hdr) const
Return pointer to the i-th spline.
real_type Splines::SplineSet::operator()(real_type x, integer spl) const
Evaluate spline value.
real_type Splines::SplineSet::eval(real_type x, integer spl) const
Referenced by dump_table.
real_type Splines::SplineSet::D(real_type x, integer spl) const
First derivative.
Referenced by eval, eval2, eval2_D, eval2_DD, eval2_DDD, eval_D, eval_DD, eval_DDD.
real_type Splines::SplineSet::eval_D(real_type x, integer spl) const
real_type Splines::SplineSet::DD(real_type x, integer spl) const
Second derivative.
Referenced by eval_DD.
real_type Splines::SplineSet::eval_DD(real_type x, integer spl) const
real_type Splines::SplineSet::DDD(real_type x, integer spl) const
Third derivative.
Referenced by eval_DDD.
real_type Splines::SplineSet::eval_DDD(real_type x, integer spl) const
real_type Splines::SplineSet::DDDD(real_type x, integer spl) const
4th derivative
real_type Splines::SplineSet::eval_DDDD(real_type x, integer spl) const
real_type Splines::SplineSet::DDDDD(real_type x, integer spl) const
5th derivative
real_type Splines::SplineSet::eval_DDDDD(real_type x, integer spl) const
real_type Splines::SplineSet::eval(real_type x, char const *name) const
Evaluate spline value.
real_type Splines::SplineSet::eval_D(real_type x, char const *name) const
First derivative.
real_type Splines::SplineSet::eval_DD(real_type x, char const *name) const
Second derivative.
real_type Splines::SplineSet::eval_DDD(real_type x, char const *name) const
Third derivative.
real_type Splines::SplineSet::eval_DDDD(real_type x, char const *name) const
4th derivative
real_type Splines::SplineSet::eval_DDDDD(real_type x, char const *name) const
5th derivative
void Splines::SplineSet::eval(real_type x, vector< real_type > &vals) const
Evaluate all the splines at x
void Splines::SplineSet::eval_D(real_type x, vector< real_type > &vals) const
Evaluate the fist derivative of all the splines at x
void Splines::SplineSet::eval_DD(real_type x, vector< real_type > &vals) const
Evaluate the second derivative of all the splines at x
void Splines::SplineSet::eval_DDD(real_type x, vector< real_type > &vals) const
Evaluate the third derivative of all the splines at x
void Splines::SplineSet::eval_DDDD(real_type x, vector< real_type > &vals) const
Evaluate the 4th derivative of all the splines at x
void Splines::SplineSet::eval_DDDDD(real_type x, vector< real_type > &vals) const
Evaluate the 5th derivative of all the splines at x
void Splines::SplineSet::eval(real_type x, real_type *const vals, integer incy=1) const
Evaluate all the splines at x
void Splines::SplineSet::eval_D(real_type x, real_type *const vals, integer incy=1) const
Evaluate the fist derivative of all the splines at x
void Splines::SplineSet::eval_DD(real_type x, real_type *const vals, integer incy=1) const
Evaluate the second derivative of all the splines at x
void Splines::SplineSet::eval_DDD(real_type x, real_type *const vals, integer incy=1) const
Evaluate the third derivative of all the splines at x
void Splines::SplineSet::eval_DDDD(real_type x, real_type *const vals, integer incy=1) const
Evaluate the 4th derivative of all the splines at x
void Splines::SplineSet::eval_DDDDD(real_type x, real_type *const vals, integer incy=1) const
Evaluate the 5th derivative of all the splines at x
void Splines::SplineSet::eval2(integer spl, real_type zeta, vector< real_type > &vals) const
Evaluate all the splines at zeta using spline[spl] as independent.
Referenced by eval2.
void Splines::SplineSet::eval2_D(integer spl, real_type zeta, vector< real_type > &vals) const
| Evaluate the fist derivative of all the splines | at zeta using spline[spl] as independent
Referenced by eval2_D.
void Splines::SplineSet::eval2_DD(integer spl, real_type zeta, vector< real_type > &vals) const
| Evaluate the second derivative of all the splines | at zeta using spline[spl] as independent
Referenced by eval2_DD.
void Splines::SplineSet::eval2_DDD(integer spl, real_type zeta, vector< real_type > &vals) const
| Evaluate the third derivative of all the splines | at zeta using spline[spl] as independent
Referenced by eval2_DDD.
void Splines::SplineSet::eval2(integer spl, real_type zeta, real_type *const vals, integer incy=1) const
Evaluate all the splines at zeta using spline[spl] as independent.
void Splines::SplineSet::eval2_D(integer spl, real_type zeta, real_type *const vals, integer incy=1) const
Evaluate the fist derivative of all the splines at zeta using spline[spl] as independent
void Splines::SplineSet::eval2_DD(integer spl, real_type zeta, real_type *const vals, integer incy=1) const
Evaluate the second derivative of all the splines at zeta using spline[spl] as independent
void Splines::SplineSet::eval2_DDD(integer spl, real_type zeta, real_type *const vals, integer incy=1) const
Evaluate the 3rd derivative of all the splines at zeta using spline[spl] as independent
real_type Splines::SplineSet::eval2(real_type zeta, char const *indep, char const *name) const
Evaluate the spline name at zeta using spline indep as independent
real_type Splines::SplineSet::eval2_D(real_type zeta, char const *indep, char const *name) const
Evaluate first derivative of the spline name at zeta using spline indep as independent
real_type Splines::SplineSet::eval2_DD(real_type zeta, char const *indep, char const *name) const
Evaluate second derivative of the spline name at zeta using spline indep as independent
real_type Splines::SplineSet::eval2_DDD(real_type zeta, char const *indep, char const *name) const
Evaluate third derivative of the spline name at zeta using spline indep as independent
real_type Splines::SplineSet::eval2(real_type zeta, integer indep, integer spl) const
Evaluate the spline spl at zeta using spline indep as independent
real_type Splines::SplineSet::eval2_D(real_type zeta, integer indep, integer spl) const
Evaluate first derivative of the spline spl at zeta using spline indep as independent
real_type Splines::SplineSet::eval2_DD(real_type zeta, integer indep, integer spl) const
Evaluate second derivative of the spline spl at zeta using spline indep as independent
real_type Splines::SplineSet::eval2_DDD(real_type zeta, integer indep, integer spl) const
Evaluate third derivative of the spline spl at zeta using spline indep as independent
void Splines::SplineSet::eval(real_type x, GenericContainer &vals) const
Evaluate all the splines at x and fill a map of values in a GenericContainer
void Splines::SplineSet::eval(vec_real_type const &vec, GenericContainer &vals) const
Evaluate all the splines at x values contained in vec and fill a map of vector in a GenericContainer
void Splines::SplineSet::eval(real_type x, vec_string_type const &columns, GenericContainer &vals) const
Evaluate all the splines at x and fill a map of values in a GenericContainer with keys in columns
void Splines::SplineSet::eval(vec_real_type const &vec, vec_string_type const &columns, GenericContainer &vals) const
Evaluate all the splines at x values contained in vec and fill a map of vector in a GenericContainer with keys in columns
void Splines::SplineSet::eval2(real_type zeta, integer indep, GenericContainer &vals) const
Evaluate all the splines at zeta and fill a map of values in a GenericContainer and indep as independent spline
void Splines::SplineSet::eval2(vec_real_type const &zetas, integer indep, GenericContainer &vals) const
Evaluate all the splines at zeta values contained in vec and fill a map of vector in a GenericContainer and indep as independent spline
void Splines::SplineSet::eval2(real_type zeta, integer indep, vec_string_type const &columns, GenericContainer &vals) const
Evaluate all the splines at zeta and fill a map of values in a GenericContainer with keys in columns and indep as independent spline
void Splines::SplineSet::eval2(vec_real_type const &zetas, integer indep, vec_string_type const &columns, GenericContainer &vals) const
Evaluate all the splines at zeta values contained in vec and fill a map of vector in a GenericContainer with keys in columns and indep as independent spline
void Splines::SplineSet::eval2(real_type zeta, char const *indep, GenericContainer &vals) const
Evaluate all the splines at zeta and fill a map of values in a GenericContainer and indep as independent spline
void Splines::SplineSet::eval2(vec_real_type const &zetas, char const *indep, GenericContainer &vals) const
Evaluate all the splines at zeta values contained in vec and fill a map of vector in a GenericContainer and indep as independent spline
void Splines::SplineSet::eval2(real_type zeta, char const *indep, vec_string_type const &columns, GenericContainer &vals) const
Evaluate all the splines at zeta and fill a map of values in a GenericContainer with keys in columns and indep as independent spline
void Splines::SplineSet::eval2(vec_real_type const &zetas, char const *indep, vec_string_type const &columns, GenericContainer &vals) const
Evaluate all the splines at zeta values contained in vec and fill a map of vector in a GenericContainer with keys in columns and indep as independent spline
void Splines::SplineSet::eval_D(real_type x, GenericContainer &vals) const
Evaluate all the splines at x and fill a map of values in a GenericContainer
void Splines::SplineSet::eval_D(vec_real_type const &vec, GenericContainer &vals) const
Evaluate all the splines at x values contained in vec and fill a map of vector in a GenericContainer
void Splines::SplineSet::eval_D(real_type x, vec_string_type const &columns, GenericContainer &vals) const
Evaluate all the splines at x and fill a map of values in a GenericContainer with keys in columns
void Splines::SplineSet::eval_D(vec_real_type const &vec, vec_string_type const &columns, GenericContainer &vals) const
Evaluate all the splines at x values contained in vec and fill a map of vector in a GenericContainer with keys in columns
void Splines::SplineSet::eval2_D(real_type zeta, integer indep, GenericContainer &vals) const
Evaluate all the splines at zeta and fill a map of values in a GenericContainer and indep as independent spline
void Splines::SplineSet::eval2_D(vec_real_type const &zetas, integer indep, GenericContainer &vals) const
Evaluate all the splines at zeta values contained in vec and fill a map of vector in a GenericContainer and indep as independent spline
void Splines::SplineSet::eval2_D(real_type zeta, integer indep, vec_string_type const &columns, GenericContainer &vals) const
Evaluate all the splines at zeta and fill a map of values in a GenericContainer with keys in columns and indep as independent spline
void Splines::SplineSet::eval2_D(vec_real_type const &zetas, integer indep, vec_string_type const &columns, GenericContainer &vals) const
Evaluate all the splines at zeta values contained in vec and fill a map of vector in a GenericContainer with keys in columns and indep as independent spline
void Splines::SplineSet::eval2_D(real_type zeta, char const *indep, GenericContainer &vals) const
Evaluate all the splines at zeta and fill a map of values in a GenericContainer and indep as independent spline
void Splines::SplineSet::eval2_D(vec_real_type const &zetas, char const *indep, GenericContainer &vals) const
Evaluate all the splines at zeta values contained in vec and fill a map of vector in a GenericContainer and indep as independent spline.
void Splines::SplineSet::eval2_D(real_type zeta, char const *indep, vec_string_type const &columns, GenericContainer &vals) const
Evaluate all the splines at zeta and fill a map of values in a GenericContainer with keys in columns and indep as independent spline
void Splines::SplineSet::eval2_D(vec_real_type const &zetas, char const *indep, vec_string_type const &columns, GenericContainer &vals) const
Evaluate all the splines at zeta values contained in vec and fill a map of vector in a GenericContainer with keys in columns and indep as independent spline
void Splines::SplineSet::eval_DD(real_type x, GenericContainer &vals) const
Evaluate all the splines at x and fill a map of values in a GenericContainer
void Splines::SplineSet::eval_DD(vec_real_type const &vec, GenericContainer &vals) const
Evaluate all the splines at x values contained in vec and fill a map of vector in a GenericContainer
void Splines::SplineSet::eval_DD(real_type x, vec_string_type const &columns, GenericContainer &vals) const
Evaluate all the splines at x and fill a map of values in a GenericContainer with keys in columns
void Splines::SplineSet::eval_DD(vec_real_type const &vec, vec_string_type const &columns, GenericContainer &vals) const
Evaluate all the splines at x values contained in vec and fill a map of vector in a GenericContainer with keys in columns
void Splines::SplineSet::eval2_DD(real_type zeta, integer indep, GenericContainer &vals) const
Evaluate all the splines at zeta and fill a map of values in a GenericContainer and indep as independent spline
void Splines::SplineSet::eval2_DD(vec_real_type const &zetas, integer indep, GenericContainer &vals) const
Evaluate all the splines at zeta values contained in vec and fill a map of vector in a GenericContainer and indep as independent spline
void Splines::SplineSet::eval2_DD(real_type zeta, integer indep, vec_string_type const &columns, GenericContainer &vals) const
Evaluate all the splines at zeta and fill a map of values in a GenericContainer with keys in columns and indep as independent spline
void Splines::SplineSet::eval2_DD(vec_real_type const &zetas, integer indep, vec_string_type const &columns, GenericContainer &vals) const
Evaluate all the splines at zeta values contained in vec and fill a map of vector in a GenericContainer with keys in columns and indep as independent spline
void Splines::SplineSet::eval2_DD(real_type zeta, char const *indep, GenericContainer &vals) const
Evaluate all the splines at zeta and fill a map of values in a GenericContainer and indep as independent spline
void Splines::SplineSet::eval2_DD(vec_real_type const &zetas, char const *indep, GenericContainer &vals) const
Evaluate all the splines at zeta values contained in vec and fill a map of vector in a GenericContainer and indep as independent spline
void Splines::SplineSet::eval2_DD(real_type zeta, char const *indep, vec_string_type const &columns, GenericContainer &vals) const
Evaluate all the splines at zeta and fill a map of values in a GenericContainer with keys in columns and indep as independent spline
void Splines::SplineSet::eval2_DD(vec_real_type const &zetas, char const *indep, vec_string_type const &columns, GenericContainer &vals) const
Evaluate all the splines at zeta values contained in vec and fill a map of vector in a GenericContainer with keys in columns and indep as independent spline
void Splines::SplineSet::eval_DDD(real_type x, GenericContainer &vals) const
Evaluate all the splines at x and fill a map of values in a GenericContainer
void Splines::SplineSet::eval_DDD(vec_real_type const &vec, GenericContainer &vals) const
Evaluate all the splines at x values contained in vec and fill a map of vector in a GenericContainer
void Splines::SplineSet::eval_DDD(real_type x, vec_string_type const &columns, GenericContainer &vals) const
Evaluate all the splines at x and fill a map of values in a GenericContainer with keys in columns
void Splines::SplineSet::eval_DDD(vec_real_type const &vec, vec_string_type const &columns, GenericContainer &vals) const
Evaluate all the splines at x values contained in vec and fill a map of vector in a GenericContainer with keys in columns
void Splines::SplineSet::eval2_DDD(real_type zeta, integer indep, GenericContainer &vals) const
Evaluate all the splines at zeta and fill a map of values in a GenericContainer and indep as independent spline
void Splines::SplineSet::eval2_DDD(vec_real_type const &zetas, integer indep, GenericContainer &vals) const
Evaluate all the splines at zeta values contained in vec and fill a map of vector in a GenericContainer and indep as independent spline
void Splines::SplineSet::eval2_DDD(real_type zeta, integer indep, vec_string_type const &columns, GenericContainer &vals) const
Evaluate all the splines at zeta and fill a map of values in a GenericContainer with keys in columns and indep as independent spline
void Splines::SplineSet::eval2_DDD(vec_real_type const &zetas, integer indep, vec_string_type const &columns, GenericContainer &vals) const
Evaluate all the splines at zeta values contained in vec and fill a map of vector in a GenericContainer with keys in columns and indep as independent spline
void Splines::SplineSet::eval2_DDD(real_type zeta, char const *indep, GenericContainer &vals) const
Evaluate all the splines at zeta and fill a map of values in a GenericContainer and indep as independent spline
void Splines::SplineSet::eval2_DDD(vec_real_type const &zetas, char const *indep, GenericContainer &vals) const
Evaluate all the splines at zeta values contained in vec and fill a map of vector in a GenericContainer and indep as independent spline
void Splines::SplineSet::eval2_DDD(real_type zeta, char const *indep, vec_string_type const &columns, GenericContainer &vals) const
Evaluate all the splines at zeta and fill a map of values in a GenericContainer with keys in columns and indep as independent spline
void Splines::SplineSet::eval2_DDD(vec_real_type const &zetas, char const *indep, vec_string_type const &columns, GenericContainer &vals) const
Evaluate all the splines at zeta values contained in vec and fill a map of vector in a GenericContainer with keys in columns and indep as independent spline
void Splines::SplineSet::build(integer nspl, integer npts, char const **headers, SplineType1D const *stype, real_type const *X, real_type const **Y, real_type const **Yp=nullptr)
Build a set of splines.
nspl the number of splines npts the number of points of each splines headers the names of the splines stype the type of each spline X pointer to X independent values Y vector of nspl pointers to Y depentendent values. Yp vector of nspl pointers to Y derivative depentendent values.
Referenced by setup.
void Splines::SplineSet::setup(GenericContainer const &gc)
Referenced by build.
void Splines::SplineSet::build(GenericContainer const &gc)
unsigned Splines::SplineSet::type() const
Return spline type (as number)
string Splines::SplineSet::info() const
Referenced by info.
void Splines::SplineSet::info(ostream_type &stream) const
void Splines::SplineSet::dump_table(ostream_type &s, integer num_points) const