Splines::Spline
string const& Splines::Spline::name() const
return the name of the spline used in the constructor
Referenced by Splines::SplineSet::build, Splines::SplineSet::get_headers, Splines::SplineSet::header, Splines::Spline1D::name.
bool Splines::Spline::is_closed() const
Referenced by Splines::Spline1D::is_closed.
void Splines::Spline::make_closed()
Referenced by Splines::Spline1D::make_closed, Splines::SplineSet::setup.
void Splines::Spline::make_opened()
Referenced by Splines::Spline1D::make_opened, Splines::SplineSet::setup.
bool Splines::Spline::is_bounded() const
Referenced by Splines::Spline1D::is_bounded.
void Splines::Spline::make_unbounded()
Referenced by Splines::Spline1D::make_unbounded, Splines::SplineSet::setup.
void Splines::Spline::make_bounded()
Referenced by Splines::Spline1D::make_bounded, Splines::SplineSet::setup.
bool Splines::Spline::is_extended_constant() const
void Splines::Spline::make_extended_constant()
Referenced by Splines::SplineSet::setup.
void Splines::Spline::make_extended_not_constant()
Referenced by Splines::SplineSet::setup.
integer Splines::Spline::numPoints() const
return the number of support points of the spline.
Referenced by Splines::Spline1D::numPoints.
real_type Splines::Spline::xNode(integer i) const
return the i-th node of the spline (x component).
Referenced by Splines::Spline1D::xNode.
real_type Splines::Spline::yNode(integer i) const
return the i-th node of the spline (y component).
Referenced by Splines::Spline1D::yNode.
real_type Splines::Spline::xBegin() const
return first node of the spline (x component).
Referenced by Splines::Spline1D::xBegin.
real_type Splines::Spline::yBegin() const
return first node of the spline (y component).
Referenced by Splines::Spline1D::yBegin.
real_type Splines::Spline::xEnd() const
return last node of the spline (x component).
Referenced by Splines::Spline1D::xEnd.
real_type Splines::Spline::yEnd() const
return last node of the spline (y component).
Referenced by Splines::Spline1D::yEnd.
real_type Splines::Spline::xMin() const
return x-minumum spline value
Referenced by dump, info, Splines::Spline1D::xMin.
real_type Splines::Spline::xMax() const
return x-maximum spline value
Referenced by dump, info, Splines::Spline1D::xMax.
real_type Splines::Spline::yMin() const
return y-minumum spline value
Referenced by info, Splines::Spline1D::yMin.
real_type Splines::Spline::yMax() const
return y-maximum spline value
Referenced by info, Splines::Spline1D::yMax.
void Splines::Spline::setOrigin(real_type x0)
change X-origin of the spline
Referenced by Splines::Spline1D::setOrigin.
void Splines::Spline::setRange(real_type xmin, real_type xmax)
change X-range of the spline
Referenced by Splines::Spline1D::setRange.
void Splines::Spline::build(GenericContainer const &gc)
Build a spline using a generic container.
Referenced by Splines::Spline1D::build, Splines::Spline1D::setup.
void Splines::Spline::build(real_type const *x, integer incx, real_type const *y, integer incy, integer n)
Build a spline.
x vector of x-coordinates incx access elements as x[0], x[incx], x[2*incx],... y vector of y-coordinates incy access elements as y[0], y[incy], y[2*incy],... n total number of points
void Splines::Spline::build(real_type const *x, real_type const *y, integer n)
Build a spline.
x vector of x-coordinates y vector of y-coordinates n total number of points
void Splines::Spline::build(vector< real_type > const &x, vector< real_type > const &y)
Build a spline.
x vector of x-coordinates y vector of y-coordinates
virtual void Splines::Spline::build()=0
Build a spline using internal stored data
Referenced by build, Splines::CubicSplineBase::build, setup.
void Splines::Spline::setup(GenericContainer const &gc)
Build a spline using a generic container.
Referenced by build.
virtual void Splines::Spline::reserve(integer npts)=0
Allocate memory for npts points.
Referenced by build, pushBack, Splines::Spline1D::reserve.
void Splines::Spline::pushBack(real_type x, real_type y)
Add a support point (x,y) to the spline.
Referenced by Splines::Spline1D::pushBack.
void Splines::Spline::dropBack()
Drop last inserted point of the spline.
Referenced by Splines::Spline1D::dropBack.
virtual void Splines::Spline::clear()=0
Cancel the support points, empty the spline.
Referenced by Splines::Spline1D::clear.
void Splines::Spline::dump(ostream_type &s, integer nintervals, char const *header="x\ty") const
dump a sample of the spline
Referenced by dump, Splines::Spline1D::dump.
void Splines::Spline::dump(char const *fname, integer nintervals, char const *header="x\ty") const
dump a sample of the spline
virtual void Splines::Spline::writeToStream(ostream_type &s) const =0
Print spline coefficients.
Referenced by Splines::Spline1D::writeToStream.
virtual real_type Splines::Spline::operator()(real_type x) const =0
Evaluate spline value.
virtual real_type Splines::Spline::D(real_type x) const =0
First derivative.
Referenced by Splines::curvature, Splines::curvature_D, Splines::curvature_DD, Splines::Spline1D::D, Splines::SplineSet::D, Splines::SplineSet::eval2_D, Splines::SplineSet::eval2_DD, Splines::SplineSet::eval2_DDD, eval_D, Splines::Spline1D::eval_D, Splines::SplineSet::eval_D.
virtual real_type Splines::Spline::DD(real_type x) const =0
Second derivative.
Referenced by Splines::curvature, Splines::curvature_D, Splines::curvature_DD, Splines::Spline1D::DD, Splines::SplineSet::DD, Splines::SplineSet::eval2_DD, Splines::SplineSet::eval2_DDD, eval_DD, Splines::Spline1D::eval_DD, Splines::SplineSet::eval_DD.
virtual real_type Splines::Spline::DDD(real_type x) const =0
Third derivative.
Referenced by Splines::curvature_D, Splines::curvature_DD, Splines::Spline1D::DDD, Splines::SplineSet::DDD, Splines::SplineSet::eval2_DDD, eval_DDD, Splines::Spline1D::eval_DDD, Splines::SplineSet::eval_DDD.
virtual real_type Splines::Spline::DDDD(real_type) const
4th derivative
Referenced by Splines::curvature_DD, Splines::Spline1D::DDDD, Splines::SplineSet::DDDD, eval_DDDD, Splines::Spline1D::eval_DDDD, Splines::SplineSet::eval_DDDD.
virtual real_type Splines::Spline::DDDDD(real_type) const
4th derivative
Referenced by Splines::Spline1D::DDDDD, Splines::SplineSet::DDDDD, eval_DDDDD, Splines::Spline1D::eval_DDDDD, Splines::SplineSet::eval_DDDDD.
real_type Splines::Spline::eval(real_type x) const
Some aliases.
Referenced by Splines::SplineSet::eval, Splines::SplineSet::eval2.
real_type Splines::Spline::eval_D(real_type x) const
Referenced by Splines::SplineSet::eval2_D, Splines::SplineSet::eval_D.
real_type Splines::Spline::eval_DD(real_type x) const
Referenced by Splines::SplineSet::eval2_DD, Splines::SplineSet::eval_DD.
real_type Splines::Spline::eval_DDD(real_type x) const
Referenced by Splines::SplineSet::eval2_DDD, Splines::SplineSet::eval_DDD.
real_type Splines::Spline::eval_DDDD(real_type x) const
real_type Splines::Spline::eval_DDDDD(real_type x) const
virtual real_type Splines::Spline::id_eval(integer ni, real_type x) const =0
Evaluate spline value when interval is known.
Referenced by Splines::Spline1D::id_eval.
virtual real_type Splines::Spline::id_D(integer ni, real_type x) const =0
First derivative.
Referenced by Splines::Spline1D::id_D.
virtual real_type Splines::Spline::id_DD(integer ni, real_type x) const =0
Second derivative.
Referenced by Splines::Spline1D::id_DD.
virtual real_type Splines::Spline::id_DDD(integer ni, real_type x) const =0
Third derivative.
Referenced by Splines::Spline1D::id_DDD.
virtual real_type Splines::Spline::id_DDDD(integer, real_type) const
4th derivative
Referenced by Splines::Spline1D::id_DDDD.
virtual real_type Splines::Spline::id_DDDDD(integer, real_type) const
4th derivative
Referenced by Splines::Spline1D::id_DDDDD.
virtual integer Splines::Spline::coeffs(real_type *const cfs, real_type *const nodes, bool transpose=false) const =0
get the piecewise polinomials of the spline
Referenced by Splines::Spline1D::coeffs.
virtual integer Splines::Spline::order() const =0
Referenced by info, Splines::Spline1D::order.
char const* Splines::Spline::type_name() const
Return spline typename.
Referenced by info, Splines::Spline1D::type_name.
virtual unsigned Splines::Spline::type() const =0
Return spline type (as number)
Referenced by Splines::Spline1D::type, type_name, yMax, yMin.
string Splines::Spline::info() const
Return a string information of the kind and order of the spline.
Referenced by Splines::Spline1D::info, Splines::SplineSet::info.
void Splines::Spline::info(ostream_type &stream) const
Print information of the kind and order of the spline.
Referenced by info.
friend class SplineSet
string Splines::Spline::m_name
bool Splines::Spline::m_curve_is_closed
bool Splines::Spline::m_curve_can_extend
bool Splines::Spline::m_curve_extended_constant
integer Splines::Spline::m_npts
integer Splines::Spline::m_npts_reserved
real_type* Splines::Spline::m_X
real_type* Splines::Spline::m_Y
Utils::BinarySearch<integer> Splines::Spline::m_bs
void Splines::Spline::initLastInterval()
Splines::Spline::Spline(Spline const &)=delete
Spline const& Splines::Spline::operator=(Spline const &)=delete
Splines::Spline::Spline(string const &name="Spline")
spline constructor
virtual Splines::Spline::~Spline()
spline destructor
integer Splines::Spline::search(real_type &x) const
find interval containing x using binary search.