Splines::SplineVec
string const Splines::SplineVec::m_name
Utils::Malloc<real_type> Splines::SplineVec::m_baseValue
Utils::Malloc<real_type*> Splines::SplineVec::m_basePointer
integer Splines::SplineVec::m_dim
integer Splines::SplineVec::m_npts
bool Splines::SplineVec::m_curve_is_closed
bool Splines::SplineVec::m_curve_can_extend
real_type* Splines::SplineVec::m_X
real_type** Splines::SplineVec::m_Y
real_type** Splines::SplineVec::m_Yp
Utils::BinarySearch<integer> Splines::SplineVec::m_bs
Splines::SplineVec::SplineVec(SplineVec const &)=delete
SplineVec const& Splines::SplineVec::operator=(SplineVec const &)=delete
void Splines::SplineVec::initLastInterval()
void Splines::SplineVec::allocate(integer dim, integer npts)
void Splines::SplineVec::computeChords()
Splines::SplineVec::SplineVec(string const &name="SplineVec")
spline constructor
Splines::SplineVec::~SplineVec()
spline destructor
integer Splines::SplineVec::search(real_type &x) const
Referenced by D, DD, DDD, eval, eval_D, eval_DD, eval_DDD, operator().
bool Splines::SplineVec::is_closed() const
void Splines::SplineVec::make_closed()
void Splines::SplineVec::make_open()
bool Splines::SplineVec::can_extend() const
void Splines::SplineVec::make_unbounded()
void Splines::SplineVec::make_buonded()
string const& Splines::SplineVec::name() const
Referenced by info.
integer Splines::SplineVec::numPoints() const
return the number of support points of the splines
integer Splines::SplineVec::dimension() const
return the number splines in the spline set
real_type const* Splines::SplineVec::xNodes() const
return the vector of values of x-nodes
real_type Splines::SplineVec::xNode(integer npt) const
return the npt-th node of the spline (x component).
real_type Splines::SplineVec::yNode(integer npt, integer j) const
return the npt-th node of the spline (y component).
real_type Splines::SplineVec::xMin() const
return x-minumum spline value
Referenced by dump_table.
real_type Splines::SplineVec::xMax() const
return x-maximum spline value
Referenced by dump_table.
real_type Splines::SplineVec::operator()(real_type x, integer i) const
Evaluate spline value.
Referenced by eval.
real_type Splines::SplineVec::eval(real_type x, integer i) const
Referenced by dump_table, eval.
real_type Splines::SplineVec::D(real_type x, integer i) const
First derivative.
Referenced by curvature, curvature_D, eval_D.
real_type Splines::SplineVec::eval_D(real_type x, integer i) const
Referenced by curvature, curvature_D, eval_D.
real_type Splines::SplineVec::DD(real_type x, integer i) const
Second derivative.
Referenced by curvature, curvature_D, eval_DD.
real_type Splines::SplineVec::eval_DD(real_type x, integer i) const
Referenced by curvature, curvature_D, eval_DD.
real_type Splines::SplineVec::DDD(real_type x, integer i) const
Third derivative.
Referenced by curvature_D, eval_DDD.
real_type Splines::SplineVec::eval_DDD(real_type x, integer i) const
Referenced by curvature_D, eval_DDD.
real_type Splines::SplineVec::DDDD(real_type x, integer i) const
4th derivative
Referenced by eval_DDDD.
real_type Splines::SplineVec::eval_DDDD(real_type x, integer i) const
Referenced by eval_DDDD.
real_type Splines::SplineVec::DDDDD(real_type x, integer i) const
5th derivative
Referenced by eval_DDDDD.
real_type Splines::SplineVec::eval_DDDDD(real_type x, integer i) const
Referenced by eval_DDDDD.
void Splines::SplineVec::eval(real_type x, real_type *const vals, integer inc) const
Evaluate all the splines at x
void Splines::SplineVec::eval_D(real_type x, real_type *const vals, integer inc) const
Evaluate the fist derivative of all the splines at x
void Splines::SplineVec::eval_DD(real_type x, real_type *const vals, integer inc) const
Evaluate the second derivative of all the splines at x
void Splines::SplineVec::eval_DDD(real_type x, real_type *const vals, integer inc) const
Evaluate the third derivative of all the splines at x
void Splines::SplineVec::eval_DDDD(real_type x, real_type *const vals, integer inc) const
Evaluate the 4th derivative of all the splines at x
void Splines::SplineVec::eval_DDDDD(real_type x, real_type *const vals, integer inc) const
Evaluate the 5th derivative of all the splines at x
void Splines::SplineVec::eval(real_type x, vector< real_type > &vals) const
Evaluate all the splines at x
void Splines::SplineVec::eval_D(real_type x, vector< real_type > &vals) const
Evaluate the fist derivative of all the splines at x
void Splines::SplineVec::eval_DD(real_type x, vector< real_type > &vals) const
Evaluate the second derivative of all the splines at x
void Splines::SplineVec::eval_DDD(real_type x, vector< real_type > &vals) const
Evaluate the third derivative of all the splines at x
void Splines::SplineVec::eval_DDDD(real_type x, vector< real_type > &vals) const
Evaluate the 4th derivative of all the splines at x
void Splines::SplineVec::eval_DDDDD(real_type x, vector< real_type > &vals) const
Evaluate the 5th derivative of all the splines at x
void Splines::SplineVec::eval(real_type x, GenericContainer &vals) const
| Evaluate at x and fill a GenericContainer
void Splines::SplineVec::eval_D(real_type x, GenericContainer &vals) const
void Splines::SplineVec::eval_DD(real_type x, GenericContainer &vals) const
void Splines::SplineVec::eval_DDD(real_type x, GenericContainer &vals) const
void Splines::SplineVec::eval_DDDD(real_type x, GenericContainer &vals) const
void Splines::SplineVec::eval_DDDDD(real_type x, GenericContainer &vals) const
void Splines::SplineVec::eval(vec_real_type const &x, GenericContainer &vals) const
| Evaluate at x and fill a GenericContainer
void Splines::SplineVec::eval_D(vec_real_type const &x, GenericContainer &vals) const
void Splines::SplineVec::eval_DD(vec_real_type const &x, GenericContainer &vals) const
void Splines::SplineVec::eval_DDD(vec_real_type const &x, GenericContainer &vals) const
void Splines::SplineVec::eval_DDDD(vec_real_type const &x, GenericContainer &vals) const
void Splines::SplineVec::eval_DDDDD(vec_real_type const &x, GenericContainer &vals) const
void Splines::SplineVec::setup(integer dim, integer npts, real_type const **Y)
Referenced by build.
void Splines::SplineVec::setup(integer dim, integer npts, real_type const *Y, integer ldY)
void Splines::SplineVec::setKnots(real_type const *X)
void Splines::SplineVec::setKnotsChordLength()
void Splines::SplineVec::setKnotsCentripetal()
void Splines::SplineVec::setKnotsFoley()
void Splines::SplineVec::CatmullRom()
real_type Splines::SplineVec::curvature(real_type x) const
real_type Splines::SplineVec::curvature_D(real_type x) const
void Splines::SplineVec::setup(GenericContainer const &gc)
void Splines::SplineVec::build(GenericContainer const &gc)
virtual unsigned Splines::SplineVec::type() const
Return spline type (as number)
string Splines::SplineVec::info() const
Referenced by info.
void Splines::SplineVec::info(ostream_type &stream) const
void Splines::SplineVec::dump_table(ostream_type &s, integer num_points) const