Splines::QuinticSplineBase
string const& Splines::Spline::name() const
return the name of the spline used in the constructor
Referenced by Splines::SplineSet::build, Splines::SplineSet::get_headers, Splines::SplineSet::header, Splines::Spline1D::name.
bool Splines::Spline::is_closed() const
Referenced by Splines::Spline1D::is_closed.
void Splines::Spline::make_closed()
Referenced by Splines::Spline1D::make_closed, Splines::SplineSet::setup.
void Splines::Spline::make_opened()
Referenced by Splines::Spline1D::make_opened, Splines::SplineSet::setup.
bool Splines::Spline::is_bounded() const
Referenced by Splines::Spline1D::is_bounded.
void Splines::Spline::make_unbounded()
Referenced by Splines::Spline1D::make_unbounded, Splines::SplineSet::setup.
void Splines::Spline::make_bounded()
Referenced by Splines::Spline1D::make_bounded, Splines::SplineSet::setup.
bool Splines::Spline::is_extended_constant() const
void Splines::Spline::make_extended_constant()
Referenced by Splines::SplineSet::setup.
void Splines::Spline::make_extended_not_constant()
Referenced by Splines::SplineSet::setup.
integer Splines::Spline::numPoints() const
return the number of support points of the spline.
Referenced by Splines::Spline1D::numPoints.
real_type Splines::Spline::xNode(integer i) const
return the i-th node of the spline (x component).
Referenced by Splines::Spline1D::xNode.
real_type Splines::Spline::yNode(integer i) const
return the i-th node of the spline (y component).
Referenced by Splines::Spline1D::yNode.
real_type Splines::Spline::xBegin() const
return first node of the spline (x component).
Referenced by Splines::Spline1D::xBegin.
real_type Splines::Spline::yBegin() const
return first node of the spline (y component).
Referenced by Splines::Spline1D::yBegin.
real_type Splines::Spline::xEnd() const
return last node of the spline (x component).
Referenced by Splines::Spline1D::xEnd.
real_type Splines::Spline::yEnd() const
return last node of the spline (y component).
Referenced by Splines::Spline1D::yEnd.
real_type Splines::Spline::xMin() const
return x-minumum spline value
Referenced by Splines::Spline::dump, Splines::Spline::info, Splines::Spline1D::xMin.
real_type Splines::Spline::xMax() const
return x-maximum spline value
Referenced by Splines::Spline::dump, Splines::Spline::info, Splines::Spline1D::xMax.
real_type Splines::Spline::yMin() const
return y-minumum spline value
Referenced by Splines::Spline::info, Splines::Spline1D::yMin.
real_type Splines::Spline::yMax() const
return y-maximum spline value
Referenced by Splines::Spline::info, Splines::Spline1D::yMax.
void Splines::Spline::setOrigin(real_type x0)
change X-origin of the spline
Referenced by Splines::Spline1D::setOrigin.
void Splines::Spline::build(GenericContainer const &gc)
Build a spline using a generic container.
Referenced by Splines::Spline1D::build, Splines::Spline1D::setup.
void Splines::Spline::build(real_type const *x, integer incx, real_type const *y, integer incy, integer n)
Build a spline.
x vector of x-coordinates incx access elements as x[0], x[incx], x[2*incx],... y vector of y-coordinates incy access elements as y[0], y[incy], y[2*incy],... n total number of points
void Splines::Spline::build(real_type const *x, real_type const *y, integer n)
Build a spline.
x vector of x-coordinates y vector of y-coordinates n total number of points
void Splines::Spline::build(vector< real_type > const &x, vector< real_type > const &y)
Build a spline.
x vector of x-coordinates y vector of y-coordinates
virtual void Splines::Spline::build()=0
Build a spline using internal stored data
Referenced by Splines::Spline::build, Splines::CubicSplineBase::build, Splines::Spline::setup.
void Splines::Spline::setup(GenericContainer const &gc)
Build a spline using a generic container.
Referenced by Splines::Spline::build.
void Splines::Spline::pushBack(real_type x, real_type y)
Add a support point (x,y) to the spline.
Referenced by Splines::Spline1D::pushBack.
void Splines::Spline::dropBack()
Drop last inserted point of the spline.
Referenced by Splines::Spline1D::dropBack.
void Splines::Spline::dump(ostream_type &s, integer nintervals, char const *header="x\ty") const
dump a sample of the spline
Referenced by Splines::Spline::dump, Splines::Spline1D::dump.
void Splines::Spline::dump(char const *fname, integer nintervals, char const *header="x\ty") const
dump a sample of the spline
real_type Splines::Spline::eval(real_type x) const
Some aliases.
Referenced by Splines::SplineSet::eval, Splines::SplineSet::eval2.
real_type Splines::Spline::eval_D(real_type x) const
Referenced by Splines::SplineSet::eval2_D, Splines::SplineSet::eval_D.
real_type Splines::Spline::eval_DD(real_type x) const
Referenced by Splines::SplineSet::eval2_DD, Splines::SplineSet::eval_DD.
real_type Splines::Spline::eval_DDD(real_type x) const
Referenced by Splines::SplineSet::eval2_DDD, Splines::SplineSet::eval_DDD.
real_type Splines::Spline::eval_DDDD(real_type x) const
real_type Splines::Spline::eval_DDDDD(real_type x) const
char const* Splines::Spline::type_name() const
Return spline typename.
Referenced by Splines::Spline::info, Splines::Spline1D::type_name.
string Splines::Spline::info() const
Return a string information of the kind and order of the spline.
Referenced by Splines::Spline1D::info, Splines::SplineSet::info.
void Splines::Spline::info(ostream_type &stream) const
Print information of the kind and order of the spline.
Referenced by Splines::Spline::info.
Utils::Malloc<real_type> Splines::QuinticSplineBase::m_baseValue
real_type* Splines::QuinticSplineBase::m_Yp
real_type* Splines::QuinticSplineBase::m_Ypp
bool Splines::QuinticSplineBase::m_external_alloc
Splines::QuinticSplineBase::QuinticSplineBase(string const &name="Spline")
spline constructor
Splines::QuinticSplineBase::~QuinticSplineBase() override
void Splines::QuinticSplineBase::copySpline(QuinticSplineBase const &S)
real_type Splines::QuinticSplineBase::ypNode(integer i) const
return the i-th node of the spline (y' component).
real_type Splines::QuinticSplineBase::yppNode(integer i) const
return the i-th node of the spline (y'' component).
void Splines::QuinticSplineBase::setRange(real_type xmin, real_type xmax)
change X-range of the spline
void Splines::QuinticSplineBase::reserve_external(integer n, real_type *&p_x, real_type *&p_y, real_type *&p_Yp, real_type *&p_Ypp)
Use externally allocated memory for npts points.
real_type Splines::QuinticSplineBase::operator()(real_type x) const override
Evaluate spline value.
real_type Splines::QuinticSplineBase::D(real_type x) const override
First derivative.
real_type Splines::QuinticSplineBase::DD(real_type x) const override
Second derivative.
real_type Splines::QuinticSplineBase::DDD(real_type x) const override
Third derivative.
real_type Splines::QuinticSplineBase::DDDD(real_type x) const override
4th derivative
real_type Splines::QuinticSplineBase::DDDDD(real_type x) const override
4th derivative
real_type Splines::QuinticSplineBase::id_eval(integer ni, real_type x) const override
Evaluate spline value when interval is known.
real_type Splines::QuinticSplineBase::id_D(integer ni, real_type x) const override
First derivative.
real_type Splines::QuinticSplineBase::id_DD(integer ni, real_type x) const override
Second derivative.
real_type Splines::QuinticSplineBase::id_DDD(integer ni, real_type x) const override
Third derivative.
real_type Splines::QuinticSplineBase::id_DDDD(integer ni, real_type x) const override
4th derivative
real_type Splines::QuinticSplineBase::id_DDDDD(integer ni, real_type x) const override
4th derivative
void Splines::QuinticSplineBase::writeToStream(ostream_type &s) const override
Print spline coefficients.
unsigned Splines::QuinticSplineBase::type() const override
Return spline type (as number)
void Splines::QuinticSplineBase::reserve(integer npts) override
Allocate memory for npts points.
void Splines::QuinticSplineBase::clear() override
Cancel the support points, empty the spline.
integer Splines::QuinticSplineBase::coeffs(real_type *const cfs, real_type *const nodes, bool transpose=false) const override
get the piecewise polinomials of the spline
integer Splines::QuinticSplineBase::order() const override
integer Splines::Spline::search(real_type &x) const
find interval containing x using binary search.