Splines
CUBIC_SPLINE_TYPE_BC
REGION_ABCDEM
QUINTIC_SPLINE_TYPE
SplineType1D
SplineType2D
typedef double Splines::real_type
Floating point type for splines.
typedef int Splines::integer
Signed integer type for splines.
typedef basic_ostream<char> Splines::ostream_type
char const * Splines::spline_type_1D[]
Referenced by Splines::Spline::type_name.
static REGION_ABCDEM Splines::get_region(real_type alpha, real_type beta)
static real_type Splines::max_abs(real_type a, real_type b)
Referenced by Pchip_build.
static real_type Splines::min_abs(real_type a, real_type b)
Referenced by Pchip_build.
static int Splines::signTest(real_type const a, real_type const b)
Referenced by Pchip_build.
void Splines::Pchip_build(real_type const *X, real_type const *Y, real_type *Yp, integer npts)
Reference: F.N. Fritsch, R.E. Carlson: Monotone Piecewise Cubic Interpolation, SIAM J. Numer. Anal. Vol 17, No. 2, April 1980 F.N. Fritsch and J. Butland: A method for constructing local monotone piecewise cubic interpolants, SIAM Journal on Scientific and Statistical Computing 5, 2 (June 1984), pp. 300-304.
Referenced by Splines::PchipSpline::build.
static void Splines::Pchip_build_new(real_type const *X, real_type const *Y, real_type *Yp, integer npts)
void Splines::uniform(integer, integer npts, real_type const *, integer, real_type *t)
Compute nodes for the spline using uniform distribution dim dimension of the points npts number of points pnts matrix whose columns are the points ld_pnts leading dimension of the matrix (fortran storage) t vector of the computed nodes
void Splines::chordal(integer dim, integer npts, real_type const *pnts, integer ld_pnts, real_type *t)
Compute nodes for the spline using chordal distribution dim dimension of the points npts number of points pnts matrix whose columns are the points ld_pnts leading dimension of the matrix (fortran storage) t vector of the computed nodes
void Splines::centripetal(integer dim, integer npts, real_type const *pnts, integer ld_pnts, real_type alpha, real_type *t)
Compute nodes for the spline using centripetal distribution dim dimension of the points npts number of points pnts matrix whose columns are the points ld_pnts leading dimension of the matrix (fortran storage) alpha power factor t vector of the computed nodes
integer Splines::checkCubicSplineMonotonicity(real_type const *X, real_type const *Y, real_type const *Yp, integer npts)
Check if cubic spline with this data is monotone, return -1 no, 0 yes, 1 strictly monotone.
Referenced by Splines::SplineSet::build.
real_type Splines::curvature(real_type s, Spline const &X, Spline const &Y)
compute curvature of a planar curve
real_type Splines::curvature_D(real_type s, Spline const &X, Spline const &Y)
compute curvature derivative of a planar curve
real_type Splines::curvature_DD(real_type s, Spline const &X, Spline const &Y)
compute curvature second derivative of a planar curve
void Splines::backtrace(ostream_type &)
void Splines::universal(integer dim, integer npts, real_type const *pnts, integer ld_pnts, real_type *t)
Compute nodes for the spline using universal distribution dim dimension of the points npts number of points pnts matrix whose columns are the points ld_pnts leading dimension of the matrix (fortran storage) t vector of the computed nodes
void Splines::FoleyNielsen(integer dim, integer npts, real_type const *pnts, integer ld_pnts, real_type *t)
Compute nodes for the spline using FoleyNielsen distribution dim dimension of the points npts number of points pnts matrix whose columns are the points ld_pnts leading dimension of the matrix (fortran storage) t vector of the computed nodes
void Splines::FangHung(integer dim, integer npts, real_type const *pnts, integer ld_pnts, real_type *t)
Compute nodes for the spline using FangHung distribution dim dimension of the points npts number of points pnts matrix whose columns are the points ld_pnts leading dimension of the matrix (fortran storage) t vector of the computed nodes
static Spline* Splines::new_Spline1D(string const &_name, SplineType1D tp)
Referenced by Splines::Spline1D::build, Splines::Spline1D::setup.