% +--------------------------------------------------------------------------+
% | 'Indigo' module version 1.0 - BSD 3-Clause License - Copyright (c) 2023  |
% | Current version authors:                                                 |
% |   Davide Stocco and Enrico Bertolazzi.                                   |
% +--------------------------------------------------------------------------+

% Matlab generated code for implicit system: DoublePendulum
% This file has been automatically generated by Indigo.
% DISCLAIMER: If you need to edit it, do it wisely!

classdef DoublePendulum < Indigo.Systems.Implicit
  %
  % No class description provided.
  %
  properties (SetAccess = protected, Hidden = true)
    % User data
    m_m__1 = 1.0;
    m_m__2 = 2.0;
    m_g = 9.81;
    m_ell__1 = 1.0;
    m_ell__2 = 1.0;
  end
  %
  methods
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function this = DoublePendulum( varargin )
      % Constructor for 'DoublePendulum' class.

      % Superclass constructor
      num_eqns = 10;
      num_veil = 0;
      num_invs = 6;
      this = this@Indigo.Systems.Implicit('DoublePendulum', num_eqns, num_veil, num_invs);

      % User data
      if (nargin == 0)
        % Keep default values
      elseif (nargin == 5)
        this.m_m__1 = varargin{1};
        this.m_m__2 = varargin{2};
        this.m_g = varargin{3};
        this.m_ell__1 = varargin{4};
        this.m_ell__2 = varargin{5};
      else
        error('wrong number of input arguments.');
      end
    end % DoublePendulum
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_F = F( this, in_1, in_2, in_3, t )
      % Evaluate the function F.

      % Extract properties
      m__1 = this.m_m__1;
      m__2 = this.m_m__2;
      g = this.m_g;
      ell__1 = this.m_ell__1;
      ell__2 = this.m_ell__2;

      % Extract inputs
      x__1 = in_1(1);
      y__1 = in_1(2);
      x__2 = in_1(3);
      y__2 = in_1(4);
      u__1 = in_1(5);
      v__1 = in_1(6);
      u__2 = in_1(7);
      v__2 = in_1(8);
      lambda__1 = in_1(9);
      lambda__2 = in_1(10);
      x__1_dot = in_2(1);
      y__1_dot = in_2(2);
      x__2_dot = in_2(3);
      y__2_dot = in_2(4);
      u__1_dot = in_2(5);
      v__1_dot = in_2(6);
      u__2_dot = in_2(7);
      v__2_dot = in_2(8);
      lambda__1_dot = in_2(9);
      lambda__2_dot = in_2(10);

      % Evaluate function
      out_1 = x__2_dot - u__2;
      out_2 = y__2_dot - v__2;
      t9 = 0.1e1 / m__2;
      out_3 = -m__1 * u__2_dot - 2 * t9 * (m__1 * x__1 * lambda__2 + m__1 * x__2 * lambda__2 - m__2 * x__1 * lambda__1);
      out_4 = -m__1 * v__2_dot - 2 * t9 * (m__1 * y__1 * lambda__2 + m__1 * y__2 * lambda__2 - m__2 * y__1 * lambda__1);
      out_5 = x__1_dot - u__1;
      out_6 = y__1_dot - v__1;
      t24 = 0.1e1 / m__1;
      out_7 = 2 * t24 * m__2 * x__1 * lambda__1 + m__2 * u__1_dot;
      t30 = x__1 ^ 2;
      t31 = y__1 ^ 2;
      t36 = g * m__1;
      t38 = x__1 * u__1;
      t41 = y__1 * v__1;
      out_8 = -4 * v__1 * v__1_dot + 4 * lambda__1_dot * t24 * (t30 + t31) + 2 * t24 * (v__1 * t36 + 8 * lambda__1 * t38 + 4 * lambda__1 * t41);
      out_9 = m__2 * v__1_dot + t24 * (2 * y__1 * lambda__1 + t36) * m__2;
      t55 = x__2 ^ 2;
      t58 = y__2 ^ 2;
      t63 = g * m__2;
      out_10 = 4 * lambda__2_dot * t9 * (2 * x__1 * x__2 + 2 * y__1 * y__2 + t30 + t31 + t55 + t58) + 2 * t9 * (8 * u__1 * x__2 * lambda__2 + 8 * u__2 * x__1 * lambda__2 + 8 * u__2 * x__2 * lambda__2 + 8 * v__1 * y__2 * lambda__2 + 8 * v__2 * y__1 * lambda__2 + 8 * v__2 * y__2 * lambda__2 + 8 * lambda__2 * t38 + 8 * lambda__2 * t41 + 3 * v__1 * t63 + 3 * v__2 * t63);

      % Store outputs
      out_F = zeros(10, 1);
      out_F(1) = out_1;
      out_F(2) = out_2;
      out_F(3) = out_3;
      out_F(4) = out_4;
      out_F(5) = out_5;
      out_F(6) = out_6;
      out_F(7) = out_7;
      out_F(8) = out_8;
      out_F(9) = out_9;
      out_F(10) = out_10;
    end % F
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_JF_x = JF_x( this, in_1, in_2, in_3, t )
      % Evaluate the Jacobian of F with respect to x.

      % Extract properties
      m__1 = this.m_m__1;
      m__2 = this.m_m__2;
      g = this.m_g;
      ell__1 = this.m_ell__1;
      ell__2 = this.m_ell__2;

      % Extract inputs
      x__1 = in_1(1);
      y__1 = in_1(2);
      x__2 = in_1(3);
      y__2 = in_1(4);
      u__1 = in_1(5);
      v__1 = in_1(6);
      u__2 = in_1(7);
      v__2 = in_1(8);
      lambda__1 = in_1(9);
      lambda__2 = in_1(10);
      x__1_dot = in_2(1);
      y__1_dot = in_2(2);
      x__2_dot = in_2(3);
      y__2_dot = in_2(4);
      u__1_dot = in_2(5);
      v__1_dot = in_2(6);
      u__2_dot = in_2(7);
      v__2_dot = in_2(8);
      lambda__1_dot = in_2(9);
      lambda__2_dot = in_2(10);

      % Evaluate function
      t1 = m__1 * lambda__2;
      t2 = m__2 * lambda__1;
      t4 = 0.1e1 / m__2;
      out_3_1 = -2 * t4 * (t1 - t2);
      t7 = 0.1e1 / m__1;
      out_7_1 = 2 * t7 * t2;
      out_8_1 = 16 * t7 * u__1 * lambda__1 + 8 * lambda__1_dot * t7 * x__1;
      out_10_1 = 4 * lambda__2_dot * t4 * (2 * x__2 + 2 * x__1) + 2 * t4 * (8 * u__1 * lambda__2 + 8 * u__2 * lambda__2);
      out_4_2 = out_3_1;
      out_8_2 = 8 * t7 * v__1 * lambda__1 + 8 * lambda__1_dot * t7 * y__1;
      out_9_2 = out_7_1;
      out_10_2 = 4 * lambda__2_dot * t4 * (2 * y__2 + 2 * y__1) + 2 * t4 * (8 * v__1 * lambda__2 + 8 * v__2 * lambda__2);
      out_3_3 = -2 * t4 * t1;
      out_10_3 = out_10_1;
      out_4_4 = out_3_3;
      out_10_4 = out_10_2;
      out_5_5 = -1;
      out_8_5 = 16 * t7 * lambda__1 * x__1;
      out_10_5 = 2 * t4 * (8 * x__1 * lambda__2 + 8 * x__2 * lambda__2);
      out_6_6 = -1;
      out_8_6 = -4 * v__1_dot + 2 * t7 * (g * m__1 + 4 * y__1 * lambda__1);
      out_10_6 = 2 * t4 * (3 * g * m__2 + 8 * y__1 * lambda__2 + 8 * y__2 * lambda__2);
      out_1_7 = -1;
      out_10_7 = out_10_5;
      out_2_8 = -1;
      out_10_8 = out_10_6;
      out_3_9 = 2 * x__1;
      out_4_9 = 2 * y__1;
      out_7_9 = 2 * t7 * m__2 * x__1;
      t68 = x__1 * u__1;
      t70 = y__1 * v__1;
      out_8_9 = 2 * t7 * (8 * t68 + 4 * t70);
      out_9_9 = 2 * t7 * y__1 * m__2;
      out_3_10 = -2 * t4 * (m__1 * x__1 + m__1 * x__2);
      out_4_10 = -2 * t4 * (m__1 * y__1 + m__1 * y__2);
      out_10_10 = 2 * t4 * (8 * u__1 * x__2 + 8 * u__2 * x__1 + 8 * u__2 * x__2 + 8 * v__1 * y__2 + 8 * v__2 * y__1 + 8 * v__2 * y__2 + 8 * t68 + 8 * t70);

      % Store outputs
      out_JF_x = zeros(10, 10);
      out_JF_x(3, 1) = out_3_1;
      out_JF_x(7, 1) = out_7_1;
      out_JF_x(8, 1) = out_8_1;
      out_JF_x(10, 1) = out_10_1;
      out_JF_x(4, 2) = out_4_2;
      out_JF_x(8, 2) = out_8_2;
      out_JF_x(9, 2) = out_9_2;
      out_JF_x(10, 2) = out_10_2;
      out_JF_x(3, 3) = out_3_3;
      out_JF_x(10, 3) = out_10_3;
      out_JF_x(4, 4) = out_4_4;
      out_JF_x(10, 4) = out_10_4;
      out_JF_x(5, 5) = out_5_5;
      out_JF_x(8, 5) = out_8_5;
      out_JF_x(10, 5) = out_10_5;
      out_JF_x(6, 6) = out_6_6;
      out_JF_x(8, 6) = out_8_6;
      out_JF_x(10, 6) = out_10_6;
      out_JF_x(1, 7) = out_1_7;
      out_JF_x(10, 7) = out_10_7;
      out_JF_x(2, 8) = out_2_8;
      out_JF_x(10, 8) = out_10_8;
      out_JF_x(3, 9) = out_3_9;
      out_JF_x(4, 9) = out_4_9;
      out_JF_x(7, 9) = out_7_9;
      out_JF_x(8, 9) = out_8_9;
      out_JF_x(9, 9) = out_9_9;
      out_JF_x(3, 10) = out_3_10;
      out_JF_x(4, 10) = out_4_10;
      out_JF_x(10, 10) = out_10_10;
    end % JF_x
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_JF_x_dot = JF_x_dot( this, in_1, in_2, in_3, t )
      % Evaluate the Jacobian of F with respect to x_dot.

      % Extract properties
      m__1 = this.m_m__1;
      m__2 = this.m_m__2;
      g = this.m_g;
      ell__1 = this.m_ell__1;
      ell__2 = this.m_ell__2;

      % Extract inputs
      x__1 = in_1(1);
      y__1 = in_1(2);
      x__2 = in_1(3);
      y__2 = in_1(4);
      u__1 = in_1(5);
      v__1 = in_1(6);
      u__2 = in_1(7);
      v__2 = in_1(8);
      lambda__1 = in_1(9);
      lambda__2 = in_1(10);
      x__1_dot = in_2(1);
      y__1_dot = in_2(2);
      x__2_dot = in_2(3);
      y__2_dot = in_2(4);
      u__1_dot = in_2(5);
      v__1_dot = in_2(6);
      u__2_dot = in_2(7);
      v__2_dot = in_2(8);
      lambda__1_dot = in_2(9);
      lambda__2_dot = in_2(10);

      % Evaluate function
      out_5_1 = 1;
      out_6_2 = 1;
      out_1_3 = 1;
      out_2_4 = 1;
      out_7_5 = m__2;
      out_8_6 = -4 * v__1;
      out_9_6 = m__2;
      out_3_7 = -m__1;
      out_4_8 = out_3_7;
      t2 = x__1 ^ 2;
      t3 = y__1 ^ 2;
      out_8_9 = 4 / m__1 * (t2 + t3);
      t9 = x__2 ^ 2;
      t12 = y__2 ^ 2;
      out_10_10 = 4 / m__2 * (2 * x__1 * x__2 + 2 * y__1 * y__2 + t12 + t2 + t3 + t9);

      % Store outputs
      out_JF_x_dot = zeros(10, 10);
      out_JF_x_dot(5, 1) = out_5_1;
      out_JF_x_dot(6, 2) = out_6_2;
      out_JF_x_dot(1, 3) = out_1_3;
      out_JF_x_dot(2, 4) = out_2_4;
      out_JF_x_dot(7, 5) = out_7_5;
      out_JF_x_dot(8, 6) = out_8_6;
      out_JF_x_dot(9, 6) = out_9_6;
      out_JF_x_dot(3, 7) = out_3_7;
      out_JF_x_dot(4, 8) = out_4_8;
      out_JF_x_dot(8, 9) = out_8_9;
      out_JF_x_dot(10, 10) = out_10_10;
    end % JF_x_dot
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_JF_v = JF_v( this, in_1, in_2, in_3, t )
      % Evaluate the Jacobian of F with respect to v.

      % Extract properties
      m__1 = this.m_m__1;
      m__2 = this.m_m__2;
      g = this.m_g;
      ell__1 = this.m_ell__1;
      ell__2 = this.m_ell__2;

      % Extract inputs
      x__1 = in_1(1);
      y__1 = in_1(2);
      x__2 = in_1(3);
      y__2 = in_1(4);
      u__1 = in_1(5);
      v__1 = in_1(6);
      u__2 = in_1(7);
      v__2 = in_1(8);
      lambda__1 = in_1(9);
      lambda__2 = in_1(10);
      x__1_dot = in_2(1);
      y__1_dot = in_2(2);
      x__2_dot = in_2(3);
      y__2_dot = in_2(4);
      u__1_dot = in_2(5);
      v__1_dot = in_2(6);
      u__2_dot = in_2(7);
      v__2_dot = in_2(8);
      lambda__1_dot = in_2(9);
      lambda__2_dot = in_2(10);

      % Evaluate function
      % No elements

      % Store outputs
      out_JF_v = zeros(10, 0);
    end % JF_v
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_v = v( this, in_1, t )
      % Evaluate the the veils v.

      % Extract properties
      m__1 = this.m_m__1;
      m__2 = this.m_m__2;
      g = this.m_g;
      ell__1 = this.m_ell__1;
      ell__2 = this.m_ell__2;

      % Extract inputs
      x__1 = in_1(1);
      y__1 = in_1(2);
      x__2 = in_1(3);
      y__2 = in_1(4);
      u__1 = in_1(5);
      v__1 = in_1(6);
      u__2 = in_1(7);
      v__2 = in_1(8);
      lambda__1 = in_1(9);
      lambda__2 = in_1(10);

      % Evaluate function
      % No elements

      % Store outputs
      out_v = zeros(0, 1);
    end % v
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_Jv_x = Jv_x( this, in_1, t )
      % Evaluate the Jacobian of v with respect to x.

      % Extract properties
      m__1 = this.m_m__1;
      m__2 = this.m_m__2;
      g = this.m_g;
      ell__1 = this.m_ell__1;
      ell__2 = this.m_ell__2;

      % Extract inputs
      x__1 = in_1(1);
      y__1 = in_1(2);
      x__2 = in_1(3);
      y__2 = in_1(4);
      u__1 = in_1(5);
      v__1 = in_1(6);
      u__2 = in_1(7);
      v__2 = in_1(8);
      lambda__1 = in_1(9);
      lambda__2 = in_1(10);

      % Evaluate function
      % No elements

      % Store outputs
      out_Jv_x = zeros(0, 10);
    end % Jv_x
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_h = h( this, in_1, in_2, t )
      % Calculate the residual of the invariants h.

      % Extract properties
      m__1 = this.m_m__1;
      m__2 = this.m_m__2;
      g = this.m_g;
      ell__1 = this.m_ell__1;
      ell__2 = this.m_ell__2;

      % Extract inputs
      x__1 = in_1(1);
      y__1 = in_1(2);
      x__2 = in_1(3);
      y__2 = in_1(4);
      u__1 = in_1(5);
      v__1 = in_1(6);
      u__2 = in_1(7);
      v__2 = in_1(8);
      lambda__1 = in_1(9);
      lambda__2 = in_1(10);

      % Evaluate function
      t1 = ell__1 ^ 2;
      t2 = x__1 ^ 2;
      t3 = y__1 ^ 2;
      out_1 = t1 - t2 - t3;
      t4 = ell__2 ^ 2;
      t5 = x__1 * x__2;
      t7 = x__2 ^ 2;
      t8 = y__1 * y__2;
      t10 = y__2 ^ 2;
      out_2 = t4 - t2 - 2 * t5 - t7 - t3 - 2 * t8 - t10;
      t11 = x__1 * u__1;
      t12 = y__1 * v__1;
      out_3 = 2 * t11 + 2 * t12;
      out_4 = 2 * u__1 * x__2 + 2 * u__2 * x__1 + 2 * u__2 * x__2 + 2 * v__1 * y__2 + 2 * v__2 * y__1 + 2 * v__2 * y__2 + 2 * t11 + 2 * t12;
      t23 = u__1 ^ 2;
      t25 = v__1 ^ 2;
      out_5 = 2 / m__1 * (g * m__1 * y__1 - t23 * m__1 - t25 * m__1 + 2 * lambda__1 * t2 + 2 * lambda__1 * t3);
      t34 = g * m__2;
      t41 = u__2 ^ 2;
      t47 = v__2 ^ 2;
      t61 = -2 * m__2 * u__1 * u__2 - 2 * m__2 * v__1 * v__2 - t23 * m__2 - t25 * m__2 - t41 * m__2 - t47 * m__2 + 2 * lambda__2 * t10 + 2 * lambda__2 * t2 + 2 * lambda__2 * t3 + y__1 * t34 + y__2 * t34 + 4 * lambda__2 * t5 + 2 * lambda__2 * t7 + 4 * lambda__2 * t8;
      out_6 = 2 / m__2 * t61;

      % Store outputs
      out_h = zeros(6, length(t));
      out_h(1) = out_1;
      out_h(2) = out_2;
      out_h(3) = out_3;
      out_h(4) = out_4;
      out_h(5) = out_5;
      out_h(6) = out_6;
    end % h
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_Jh_x = Jh_x( this, in_1, in_2, t )
      % Calculate the Jacobian of h with respect to x.

      % Extract properties
      m__1 = this.m_m__1;
      m__2 = this.m_m__2;
      g = this.m_g;
      ell__1 = this.m_ell__1;
      ell__2 = this.m_ell__2;

      % Extract inputs
      x__1 = in_1(1);
      y__1 = in_1(2);
      x__2 = in_1(3);
      y__2 = in_1(4);
      u__1 = in_1(5);
      v__1 = in_1(6);
      u__2 = in_1(7);
      v__2 = in_1(8);
      lambda__1 = in_1(9);
      lambda__2 = in_1(10);

      % Evaluate function
      t1 = 2 * x__1;
      out_1_1 = -t1;
      out_2_1 = -2 * x__1 - 2 * x__2;
      out_3_1 = 2 * u__1;
      out_4_1 = 2 * u__1 + 2 * u__2;
      t5 = 0.1e1 / m__1;
      out_5_1 = 8 * t5 * lambda__1 * x__1;
      t11 = 0.1e1 / m__2;
      out_6_1 = 2 * t11 * (4 * x__1 * lambda__2 + 4 * x__2 * lambda__2);
      t13 = 2 * y__1;
      out_1_2 = -t13;
      out_2_2 = -2 * y__1 - 2 * y__2;
      out_3_2 = 2 * v__1;
      out_4_2 = 2 * v__1 + 2 * v__2;
      out_5_2 = 2 * t5 * (g * m__1 + 4 * y__1 * lambda__1);
      out_6_2 = 2 * t11 * (g * m__2 + 4 * y__1 * lambda__2 + 4 * y__2 * lambda__2);
      out_2_3 = out_2_1;
      out_4_3 = out_4_1;
      out_6_3 = out_6_1;
      out_2_4 = out_2_2;
      out_4_4 = out_4_2;
      out_6_4 = out_6_2;
      out_3_5 = t1;
      out_4_5 = -out_2_3;
      out_5_5 = -4 * u__1;
      out_6_5 = 2 * t11 * (-2 * m__2 * u__1 - 2 * m__2 * u__2);
      out_3_6 = t13;
      out_4_6 = -out_2_4;
      out_5_6 = -4 * v__1;
      out_6_6 = 2 * t11 * (-2 * m__2 * v__1 - 2 * m__2 * v__2);
      out_4_7 = out_4_5;
      out_6_7 = out_6_5;
      out_4_8 = out_4_6;
      out_6_8 = out_6_6;
      t40 = x__1 ^ 2;
      t41 = y__1 ^ 2;
      out_5_9 = 2 * t5 * (2 * t40 + 2 * t41);
      t48 = x__2 ^ 2;
      t53 = y__2 ^ 2;
      out_6_10 = 2 * t11 * (4 * x__1 * x__2 + 4 * y__1 * y__2 + 2 * t40 + 2 * t41 + 2 * t48 + 2 * t53);

      % Store outputs
      out_Jh_x = zeros(6, 10);
      out_Jh_x(1, 1) = out_1_1;
      out_Jh_x(2, 1) = out_2_1;
      out_Jh_x(3, 1) = out_3_1;
      out_Jh_x(4, 1) = out_4_1;
      out_Jh_x(5, 1) = out_5_1;
      out_Jh_x(6, 1) = out_6_1;
      out_Jh_x(1, 2) = out_1_2;
      out_Jh_x(2, 2) = out_2_2;
      out_Jh_x(3, 2) = out_3_2;
      out_Jh_x(4, 2) = out_4_2;
      out_Jh_x(5, 2) = out_5_2;
      out_Jh_x(6, 2) = out_6_2;
      out_Jh_x(2, 3) = out_2_3;
      out_Jh_x(4, 3) = out_4_3;
      out_Jh_x(6, 3) = out_6_3;
      out_Jh_x(2, 4) = out_2_4;
      out_Jh_x(4, 4) = out_4_4;
      out_Jh_x(6, 4) = out_6_4;
      out_Jh_x(3, 5) = out_3_5;
      out_Jh_x(4, 5) = out_4_5;
      out_Jh_x(5, 5) = out_5_5;
      out_Jh_x(6, 5) = out_6_5;
      out_Jh_x(3, 6) = out_3_6;
      out_Jh_x(4, 6) = out_4_6;
      out_Jh_x(5, 6) = out_5_6;
      out_Jh_x(6, 6) = out_6_6;
      out_Jh_x(4, 7) = out_4_7;
      out_Jh_x(6, 7) = out_6_7;
      out_Jh_x(4, 8) = out_4_8;
      out_Jh_x(6, 8) = out_6_8;
      out_Jh_x(5, 9) = out_5_9;
      out_Jh_x(6, 10) = out_6_10;
    end % Jh_x
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_Jh_v = Jh_v( this, in_1, in_2, t )
      % Calculate the Jacobian of h with respect to v.

      % Extract properties
      m__1 = this.m_m__1;
      m__2 = this.m_m__2;
      g = this.m_g;
      ell__1 = this.m_ell__1;
      ell__2 = this.m_ell__2;

      % Extract inputs
      x__1 = in_1(1);
      y__1 = in_1(2);
      x__2 = in_1(3);
      y__2 = in_1(4);
      u__1 = in_1(5);
      v__1 = in_1(6);
      u__2 = in_1(7);
      v__2 = in_1(8);
      lambda__1 = in_1(9);
      lambda__2 = in_1(10);

      % Evaluate function
      % No elements

      % Store outputs
      out_Jh_v = zeros(6, 0);
    end % Jh_v
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
  end
end % DoublePendulum

% That's All Folks!
